name: Build Privacy Scrub APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'
    
    - name: Install Cordova
      run: |
        npm install -g cordova@12.0.0
    
    - name: Create Cordova project
      run: |
        cordova create privacy-scrub com.privacyscrub.app "Privacy Scrub"
        cd privacy-scrub
        
        # Replace default index.html
        cat > www/index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width">
            <title>Privacy Scrub</title>
            <style>
                * { margin: 0; padding: 0; box-sizing: border-box; }
                body {
                    font-family: -apple-system, BlinkMacSystemFont, sans-serif;
                    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                    min-height: 100vh;
                    display: flex;
                    align-items: center;
                    justify-content: center;
                    color: white;
                    padding: 20px;
                }
                .app {
                    text-align: center;
                    background: rgba(255,255,255,0.1);
                    padding: 40px 30px;
                    border-radius: 20px;
                    backdrop-filter: blur(10px);
                    max-width: 400px;
                    width: 100%;
                }
                h1 {
                    font-size: 2.5em;
                    margin-bottom: 10px;
                    font-weight: 300;
                }
                .subtitle {
                    font-size: 1.1em;
                    opacity: 0.9;
                    margin-bottom: 30px;
                }
                .features {
                    text-align: left;
                    margin: 20px 0;
                }
                .feature {
                    margin: 12px 0;
                    padding-left: 20px;
                    position: relative;
                    font-size: 0.95em;
                }
                .feature:before {
                    content: "✓";
                    position: absolute;
                    left: 0;
                    color: #4ade80;
                    font-weight: bold;
                }
                .status {
                    margin-top: 30px;
                    padding: 15px;
                    background: rgba(255,255,255,0.1);
                    border-radius: 10px;
                    font-size: 0.9em;
                }
            </style>
        </head>
        <body>
            <div class="app">
                <h1>Privacy Scrub</h1>
                <p class="subtitle">Personal Information Protection</p>
                <div class="features">
                    <div class="feature">Find your data across websites</div>
                    <div class="feature">Automated removal requests</div>
                    <div class="feature">Privacy monitoring</div>
                    <div class="feature">Secure payments</div>
                </div>
                <div class="status">
                    App successfully built and ready for deployment
                </div>
            </div>
            <script src="cordova.js"></script>
        </body>
        </html>
        EOF
    
    - name: Add Android platform
      run: |
        cd privacy-scrub
        cordova platform add android@12.0.1
    
    - name: Build APK
      run: |
        cd privacy-scrub
        cordova build android --debug
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: privacy-scrub-cordova-apk
        path: privacy-scrub/platforms/android/app/build/outputs/apk/debug/app-debug.apk