name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Extract Android project
      run: |
        echo "Looking for Android archive..."
        ls -la
        if [ -f privacy-scrub-android.tar.gz ]; then
          echo "Extracting Android project..."
          tar -xzf privacy-scrub-android.tar.gz
          echo "Contents after extraction:"
          ls -la
          if [ -d android ]; then
            echo "Android folder found, contents:"
            ls -la android/
          fi
        else
          echo "ERROR: privacy-scrub-android.tar.gz not found"
          exit 1
        fi
    
    - name: Make gradlew executable
      run: |
        if [ -f android/gradlew ]; then
          chmod +x android/gradlew
          echo "Made gradlew executable"
        else
          echo "ERROR: gradlew not found"
          exit 1
        fi
    
    - name: Build APK
      run: |
        cd android
        echo "Building APK..."
        ./gradlew assembleDebug --stacktrace
    
    - name: Verify APK exists
      run: |
        echo "Checking for built APK..."
        find android -name "*.apk" -type f
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: privacy-scrub-apk
        path: android/app/build/outputs/apk/debug/*.apk
        if-no-files-found: error