name: Build Privacy Scrub APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Install Capacitor
      run: |
        npm install -g @capacitor/cli@5.7.0
    
    - name: Create basic web app
      run: |
        mkdir -p www
        cat > www/index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Privacy Scrub</title>
          <style>
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body { 
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
              background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
              min-height: 100vh;
              display: flex;
              align-items: center;
              justify-content: center;
              color: white;
            }
            .container { 
              text-align: center; 
              padding: 40px 20px;
              background: rgba(255,255,255,0.1);
              border-radius: 20px;
              backdrop-filter: blur(10px);
              max-width: 400px;
            }
            h1 { 
              font-size: 2.5em; 
              margin-bottom: 20px;
              font-weight: 300;
            }
            p { 
              font-size: 1.1em; 
              line-height: 1.6; 
              opacity: 0.9;
              margin-bottom: 15px;
            }
            .features {
              margin-top: 30px;
              text-align: left;
            }
            .feature {
              margin: 10px 0;
              padding-left: 20px;
              position: relative;
            }
            .feature:before {
              content: "✓";
              position: absolute;
              left: 0;
              color: #4ade80;
              font-weight: bold;
            }
          </style>
        </head>
        <body>
          <div class="container">
            <h1>Privacy Scrub</h1>
            <p>Your Personal Information Protection App</p>
            <div class="features">
              <div class="feature">Find your data across the web</div>
              <div class="feature">Automated removal requests</div>
              <div class="feature">Real-time privacy monitoring</div>
              <div class="feature">Secure payment processing</div>
            </div>
          </div>
        </body>
        </html>
        EOF
    
    - name: Initialize Capacitor
      run: |
        npx cap init "Privacy Scrub" "com.privacyscrub.app" --web-dir=www
    
    - name: Add Android platform
      run: npx cap add android
    
    - name: Sync project
      run: npx cap sync android
    
    - name: Build APK
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: privacy-scrub-android-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk