name: Build Privacy Scrub APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Install Capacitor
      run: |
        npm install -g @capacitor/cli@latest
        npm install @capacitor/core@latest @capacitor/android@latest
    
    - name: Build web assets
      run: |
        # Check if we have a built web app
        if [ -d "client" ] && [ -f "package.json" ]; then
          echo "Building existing web app..."
          npm install
          npm run build || echo "Build failed, creating fallback"
        fi
        
        # Ensure we have a dist folder with content
        mkdir -p dist
        if [ ! -f dist/index.html ]; then
          cat > dist/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Privacy Scrub</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background: #f5f5f5; }
            .container { max-width: 600px; margin: 0 auto; background: white; padding: 20px; border-radius: 8px; }
            h1 { color: #333; text-align: center; }
            p { color: #666; line-height: 1.6; }
          </style>
        </head>
        <body>
          <div class="container">
            <h1>Privacy Scrub</h1>
            <p>Your comprehensive privacy protection application.</p>
            <p>This app helps you find and remove your personal information from people search and background check websites.</p>
          </div>
        </body>
        </html>
        EOF
        fi
    
    - name: Initialize Capacitor
      run: |
        # Check if capacitor.config.ts exists
        if [ -f capacitor.config.ts ]; then
          echo "Using existing Capacitor config"
        else
          npx cap init "Privacy Scrub" "com.privacyscrub.app" --web-dir=dist
        fi
    
    - name: Add Android platform
      run: |
        if [ ! -d android ]; then
          npx cap add android
        else
          echo "Android platform already exists"
        fi
    
    - name: Copy web assets and sync
      run: |
        npx cap copy android
        npx cap sync android
    
    - name: Accept Android licenses
      run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
    
    - name: Build APK
      run: |
        cd android
        ls -la
        if [ -f gradlew ]; then
          chmod +x gradlew
          echo "Building APK..."
          ./gradlew clean assembleDebug --no-daemon --stacktrace --info
        else
          echo "gradlew not found, listing contents:"
          find . -name "gradlew*" -type f
          exit 1
        fi
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: privacy-scrub-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        if-no-files-found: error
